//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerBilling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Master
    {
        public int Item_ID { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Item_qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Category { get; set; }
    }
}
